<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

In [1]:
import numpy as np

In [3]:
A = np.array([[4,-3,1],
             [2,1,3],
             [-1,2,-5]], dtype=np.dtype(float))
b = np.array([-10,0,17])
print( A)

[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]


In [7]:
b.shape


(3,)

### Find the det

In [9]:
A_det = np.linalg.det(A)
print(A_det)

-60.000000000000036
